name: pinpointing_radio_devices
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.7.22=h56e8100_0
  - cudatoolkit=11.2.2=h7d7167e_12
  - cudnn=8.1.0.77=h3e0f4f4_0
  - libffi=3.4.2=h8ffe710_5
  - libsqlite=3.43.2=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_5
  - openssl=3.1.4=hcfcfb64_0
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.9.18=h4de0772_0_cpython
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.13=hcfcfb64_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hdcecf7f_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - pip:
      - absl-py==2.0.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.0
      - astunparse==1.6.3
      - backcall==0.2.0
      - cachetools==5.3.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.1
      - colorama==0.4.6
      - comm==0.1.4
      - compress-pickle==2.1.0
      - contourpy==1.1.1
      - coverage==7.6.9
      - cycler==0.12.1
      - daal==2024.5.0
      - daal4py==2024.5.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - drjit==0.4.3
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - gast==0.4.0
      - google-auth==2.23.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.59.0
      - h5py==3.10.0
      - hydra-core==1.3.2
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - ipydatawidgets==4.3.2
      - ipykernel==6.26.0
      - ipython==8.16.1
      - ipywidgets==8.0.5
      - jedi==0.19.1
      - joblib==1.3.2
      - jupyter-client==8.5.0
      - jupyter-core==5.5.0
      - jupyterlab-widgets==3.0.5
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - loess==2.1.2
      - markdown==3.5
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mitsuba==3.4.0
      - nest-asyncio==1.5.8
      - numpy==1.26.1
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.1.2
      - parso==0.8.3
      - pickleshare==0.7.5
      - pillow==10.1.0
      - platformdirs==3.11.0
      - plotbin==3.1.7
      - prompt-toolkit==3.0.39
      - protobuf==3.19.6
      - psutil==5.9.6
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pythreejs==2.4.2
      - pytz==2023.3.post1
      - pywin32==306
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scanf==1.5.2
      - scikit-learn==1.3.2
      - scikit-learn-intelex==2024.5.0
      - scipy==1.11.3
      - seaborn==0.13.0
      - sionna==0.16.2
      - six==1.16.0
      - stack-data==0.6.3
      - tbb==2021.13.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.12.0
      - traittypes==0.2.1
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.0.7
      - wcwidth==0.2.8
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - wrapt==1.15.0
      - zipp==3.17.0
